version: '2'
services:
  app:
    build: .
    image: opensouth
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
      - ./logs/opensouth:/var/log/opensouth
    links:
      - postgres
    environment:
      - DB_DEFAULT_HOST=${DB_DEFAULT_HOST}
      - DB_DEFAULT_PORT=${DB_DEFAULT_PORT}
      - DB_DEFAULT_USER=${DB_DEFAULT_USER}
      - DB_DEFAULT_PASSWORD=${DB_DEFAULT_PASSWORD}
      - DB_DEFAULT_NAME=${DB_DEFAULT_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  postgres:
    image: postgres
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data/pgdata
      - ./logs/postgresql:/var/log/postgresql
    environment:
      - POSTGRES_USER=${DB_DEFAULT_USER}
      - POSTGRES_PASSWORD=${DB_DEFAULT_PASSWORD}
      - POSTGRES_DB=${DB_DEFAULT_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
